config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  extend SystemAdminRoutes
  extend ApiRoutes

  get :ping, controller: :heartbeat
  get :healthcheck, controller: :heartbeat
  get :sha, controller: :heartbeat

  get "/accessibility", to: "pages#accessibility", as: :accessibility
  get "/privacy-policy", to: "pages#privacy_policy", as: :privacy_policy
  get "/guidance", to: "pages#guidance"
  get "/check-data", to: "pages#check_data"

  get "/404", to: "errors#not_found", via: :all, as: :not_found
  get "/422", to: "errors#unprocessable_entity", via: :all
  get "/500", to: "errors#internal_server_error", via: :all

  get "/trainees/not-supported-route", to: "trainees/not_supported_routes#index"

  get "/sign-in" => "sign_in#index"
  get "/sign-out" => "sign_out#index"

  get "/sign-in/user-not-found", to: "sign_in#new"

  get "request-an-account", to: "request_an_account#index"

  if FeatureService.enabled?("use_dfe_sign_in")
    get "/auth/dfe/callback" => "sessions#callback"
    get "/auth/dfe/sign-out" => "sessions#signout"
  else
    get "/personas", to: "personas#index"
    get "/auth/developer/sign-out", to: "sessions#signout"
    post "/auth/developer/callback", to: "sessions#callback"
  end

  concern :confirmable do
    resource :confirm_details, as: :confirm, only: %i[show update], path: "/confirm", controller: "/trainees/confirm_details"
  end

  resources :drafts, only: :index

  resources :trainees, except: :edit do
    scope module: :trainees do
      resource :training_details, concerns: :confirmable, only: %i[edit update], path: "/training-details"
      resource :course_years, only: %i[edit update], path: "/course-years"
      resource :publish_course_details, only: %i[edit update], path: "/publish-course-details" do
        concerns :confirmable
      end

      resource :course_details, only: %i[edit update], path: "/course-details" do
        concerns :confirmable
        resource :itt_dates, only: %i[edit update], path: "/itt-dates"
        resource :study_mode, only: %i[edit update], path: "/study-mode"
      end

      resource :confirm_deletes, only: :show, path: "/confirm-delete", as: :confirm_delete
      resource :check_details, only: :show, path: "/check-details"
      resource :review_drafts, only: :show, path: "/review-draft"
      resource :course_details, only: %i[edit update], path: "/course-details", path_names: { edit: "" }
      resource :publish_course_details, only: %i[edit update], path: "/publish-course-details", path_names: { edit: "" }

      resource :schools, concerns: :confirmable, only: %i[edit update], path: "/schools"
      resource :contact_details, concerns: :confirmable, only: %i[edit update], path: "/contact-details"
      resource :start_date, concerns: :confirmable, only: %i[edit update], path: "/trainee-start-date"
      resource :start_status, concerns: :confirmable, only: %i[edit update], path: "/trainee-start-status"
      resource :training_route, only: %i[edit update], path: "/training-routes"
      resource :course_education_phase, only: %i[edit update], path: "/course-education-phase"

      namespace :degrees do
        resource :confirm_details, as: :confirm, only: %i[show update], path: "/confirm", controller: "confirm_details"
        get "/new/type", to: "type#new"
        post "/new/type", to: "type#create"
      end

      resources :degrees, only: %i[new edit create update destroy]

      namespace :funding do
        concerns :confirmable
        resource :training_initiative, only: %i[edit update], path: "/training-initiative"
        resource :bursary, only: %i[edit update], path: "/bursary"
      end

      resource :language_specialisms, only: %i[edit update], path: "/language-specialisms"

      resource :personal_details, concerns: :confirmable, only: %i[show edit update], path: "/personal-details"

      namespace :diversity do
        resource :confirm_details, as: :confirm, only: %i[show update], path: "/confirm", controller: "confirm_details"
        resource :disclosure, only: %i[edit update], path: "/information-disclosed"
        resource :ethnic_group, only: %i[edit update], path: "/ethnic-group"
        resource :ethnic_background, only: %i[edit update], path: "/ethnic-background"
        resource :disability_disclosure, only: %i[edit update], path: "/disability-disclosure"
        resource :disability_detail, only: %i[edit update], path: "/disabilities"
      end

      resource :outcome_details, only: [], path: "outcome-details" do
        get "confirm"
        get "recommended"
        resource :outcome_date, only: %i[edit update], path: "/outcome-date"
      end

      resource :award_recommendations, only: %i[create]

      resource :confirm_withdrawal, only: %i[show update], path: "/withdraw/confirm"
      resource :withdrawal, only: %i[show update], path: "/withdraw"

      resource :confirm_deferral, only: %i[show update], path: "/defer/confirm"
      resource :deferral, only: %i[show update], path: "/defer"

      resource :confirm_reinstatement, only: %i[show update], path: "/reinstate/confirm"
      resource :reinstatement, only: %i[show update], path: "/reinstate"

      resources :lead_schools, only: %i[index], path: "/lead-schools"
      resource :lead_schools, only: %i[update edit], path: "/lead-schools"
      resources :employing_schools, only: %i[index], path: "/employing-schools"
      resource :employing_schools, only: %i[update edit], path: "/employing-schools"

      namespace :apply_applications, path: "/apply-application" do
        resource :trainee_data, only: %i[update edit], path: "/trainee-data"
        resource :course_details, only: %i[update edit], path: "/course-details"
        resource :confirm_courses, only: %i[show update], path: "/confirm-course"
      end

      resource :timeline, only: :show

      resource :subject_specialism, only: %i[edit update], path: "/subject-specialism/:position"
      resource :start_date_verification, only: %i[show update], path: "/start-date-verification"
      resource :forbidden_deletes, only: %i[show create], path: "/delete-forbidden"
      resource :forbidden_withdrawal, only: %i[show], path: "/withdrawal-forbidden"
    end
  end

  resources :trn_submissions, only: %i[create show], param: :trainee_id, path: "trainee-registrations"
  resource :cookie_preferences, only: %i[show update], path: "/cookies"

  resources :service_updates, only: %i[index], path: "service-updates"

  root to: "pages#start"
end

app/controllers/system_admin/dttp_providers_controller.rb
# frozen_string_literal: true

module SystemAdmin
  class DttpProvidersController < ApplicationController
    def index
      @providers = filtered_providers.page(params[:page] || 1)
    end

    def show
      @provider = authorize(Dttp::Provider.find(params[:id]))
    end

    def create
      @provider = authorize(Provider.create!(provider_params))
      redirect_to(provider_path(@provider))
    end

  private

    def filtered_providers
      SystemAdmin::Dttp::Providers::Filter.call(providers: find_providers, params: filter_params)
    end

    def find_providers
      authorize(::Dttp::Provider.left_outer_joins(:provider).order(:name))
    end

    def filter_params
      @filter_params ||= params.permit(:text_search).presence
    end

    def dttp_provider
      @dttp_provider ||= ::Dttp::Provider.find(params[:dttp_provider_id])
    end

    def provider_params
      dttp_provider.attributes.symbolize_keys.slice(:name, :dttp_id, :ukprn)
    end
  end
end

app/controllers/system_admin/dttp_users_controller.rb
# frozen_string_literal: true

module SystemAdmin
  class DttpUsersController < ApplicationController
    def index
      @users_view = UsersView.new(provider)
    end

  private

    def provider
      @provider ||= Provider.find(params[:provider_id])
    end
  end
end

app/controllers/system_admin/imports/users_controller.rb
# frozen_string_literal: true

module SystemAdmin
  module Imports
    class UsersController < ApplicationController
      def create
        authorize(provider.users.create!(user_params))
        redirect_to(provider_path(provider))
      end

    private

      def provider
        @provider ||= Provider.find(params[:provider_id])
      end

      def dttp_user
        @dttp_user ||= ::Dttp::User.find(params[:dttp_user_id])
      end

      def user_params
        dttp_user.attributes.symbolize_keys.slice(:first_name, :last_name, :email, :dttp_id)
      end
    end
  end
end

app/controllers/system_admin/lead_schools_controller.rb
# frozen_string_literal: true

module SystemAdmin
  class LeadSchoolsController < ApplicationController
    def index
      @lead_schools = policy_scope(School, policy_scope_class: LeadSchoolPolicy::Scope).order_by_name.page(params[:page] || 1)
    end

    def show
      @lead_school = authorize(School.lead_only.find(params[:id]), policy_class: LeadSchoolPolicy)
    end
  end
end

app/controllers/system_admin/providers_controller.rb
# frozen_string_literal: true

module SystemAdmin
  class ProvidersController < ApplicationController
    before_action :set_provider, only: %i[show edit update]

    def index
      @providers = authorize(Provider.all.order(:name))
    end

    def new
      @provider = authorize(Provider.new)
    end

    def create
      @provider = authorize(Provider.new(provider_params))

      if @provider.save
        redirect_to(providers_path)
      else
        render(:new)
      end
    end

    def show
      @users_view = UsersView.new(@provider)
    end

    def edit; end

    def update
      if @provider.update(provider_params)
        redirect_to(providers_path)
      else
        render(:edit)
      end
    end

  private

    def provider_params
      params.require(:provider).permit(:name, :dttp_id, :code, :apply_sync_enabled)
    end

    def set_provider
      @provider = authorize(Provider.find(params[:id]))
    end
  end
end

app/controllers/system_admin/schools_controller.rb
# frozen_string_literal: true

module SystemAdmin
  class SchoolsController < ApplicationController
    def index
      @schools = policy_scope(School).order_by_name.page(params[:page] || 1)
    end
  end
end

app/controllers/system_admin/users_controller.rb
# frozen_string_literal: true

module SystemAdmin
  class UsersController < ApplicationController
    def new
      @user = authorize(provider.users.build)
    end

    def create
      @user = authorize(provider.users.build(permitted_attributes(User)))
      if @user.save
        redirect_to(provider_path(provider), flash: { success: t(".success") })
      else
        render(:new)
      end
    end

    def edit
      user
      @provider = user.provider
    end

    def update
      user
      @provider = user.provider
      if user.update(permitted_attributes(@user))
        redirect_to(provider_path(provider), flash: { success: t(".success") })
      else
        render(:edit)
      end
    end

    def delete
      user
      @provider = user.provider
    end

    def destroy
      user.discard
      @provider = user.provider
      redirect_to(provider_path(@provider))
    end

  private

    def provider
      @provider ||= Provider.find(params[:provider_id])
    end

    def user
      @user ||= authorize(User.find(params[:id]))
    end
  end
end

app/controllers/system_admin/validation_errors_controller.rb
# frozen_string_literal: true

module SystemAdmin
  class ValidationErrorsController < ApplicationController
    def index
      authorize(ValidationError, :index?)
      @grouped_counts = ValidationError.group(:form_object).order("count_all DESC").count
      @grouped_column_error_counts = ValidationError.list_of_distinct_errors_with_count
    end
  end
end

app/controllers/trainees/lead_schools_controller.rb
# frozen_string_literal: true

module Trainees
  class LeadSchoolsController < BaseController
    before_action :validate_form_completeness

    helper_method :query

    def index
      @lead_school_form = Schools::LeadSchoolForm.new(trainee)
      @school_search = SchoolSearch.call(query: query, lead_schools_only: true)
    end

    def edit
      @lead_school_form = Schools::LeadSchoolForm.new(trainee)
    end

    def update
      @lead_school_form = Schools::LeadSchoolForm.new(trainee, params: trainee_params, user: current_user)

      if @lead_school_form.school_not_selected? && @lead_school_form.valid?
        return redirect_to(trainee_lead_schools_path(@trainee, query: query))
      end

      if @lead_school_form.stash_or_save!
        redirect_to(step_wizard.next_step)
      else
        @school_search = SchoolSearch.call(query: params[:query], lead_schools_only: true)
        render(index_or_edit_page)
      end
    end

  private

    def trainee_params
      params.fetch(:schools_lead_school_form, {})
            .permit(*Schools::LeadSchoolForm::FIELDS,
                    *Schools::LeadSchoolForm::NON_TRAINEE_FIELDS)
    end

    def query
      # Order important here including the use of presence() on the first hash lookup to ensure that if the user
      # submits the form with results but hasn't made a choice, we re-render the page with the previous results
      # including a validation message. Even though the search again field is hidden in this scenario, it will be
      # included in the form data, therefore we have to take that into account.
      trainee_params[:results_search_again_query].presence || trainee_params[:no_results_search_again_query] || trainee_params[:query] || params[:query]
    end

    def index_or_edit_page
      @lead_school_form.search_results_found? || @lead_school_form.no_results_searching_again? ? :index : :edit
    end

    def authorize_trainee
      authorize(trainee, :requires_schools?)
    end

    def step_wizard
      @step_wizard ||= Wizards::SchoolsStepWizard.new(trainee: trainee, page_tracker: page_tracker)
    end

    def validate_form_completeness
      return if trainee.lead_school_id.blank?
      return if user_came_from_backlink?

      redirect_to(step_wizard.start_point) if step_wizard.start_point.present?
    end
  end
end

app/views/system_admin/lead_schools/index.html.erb
<%= render PageTitle::View.new(i18n_key: "lead_schools.index") %>

<h1 class="govuk-heading-l">Lead schools</h1>

<%= render "system_admin/tab_nav" %>

<table class="govuk-table" summary="Lead schools list">
  <thead class="govuk-table__head">
    <tr class="govuk-table__row">
      <th scope="col" class="govuk-table__header govuk-!-width-one-half no-wrap">Lead school name</th>
      <th scope="col" class="govuk-table__header govuk-!-width-one-half no-wrap">URN</th>
      <th scope="col" class="govuk-table__header govuk-!-width-one-half no-wrap">Town</th>
      <th scope="col" class="govuk-table__header govuk-!-width-one-half no-wrap">Postcode</th>
      <th scope="col" class="govuk-table__header govuk-!-width-one-half no-wrap">Open date</th>
      <th scope="col" class="govuk-table__header govuk-!-width-one-half no-wrap">Close date</th>
    </tr>
  </thead>

  <tbody class="govuk-table__body">
    <% @lead_schools.each do |lead_school| %>
      <tr class="govuk-table__row qa-lead_school_row">

        <td class="govuk-table__cell">
          <span class="govuk-!-display-block govuk-!-margin-bottom-1">
            <%= govuk_link_to(lead_school.name, lead_school_path(lead_school)) %>
          </span>
        </td>

        <td class="govuk-table__cell">
          <span class="govuk-!-display-block govuk-!-margin-bottom-1">
            <%= lead_school.urn %>
          </span>
        </td>

        <td class="govuk-table__cell">
          <span class="govuk-!-display-block govuk-!-margin-bottom-1">
            <%= lead_school.town %>
          </span>
        </td>

        <td class="govuk-table__cell">
          <span class="govuk-!-display-block govuk-!-margin-bottom-1 no-wrap">
            <%= lead_school.postcode %>
          </span>
        </td>

        <td class="govuk-table__cell">
          <span class="govuk-!-display-block govuk-!-margin-bottom-1 no-wrap">
            <%= lead_school.open_date&.strftime("%d %B %Y") %>
          </span>
        </td>

        <td class="govuk-table__cell">
          <span class="govuk-!-display-block govuk-!-margin-bottom-1 no-wrap">
            <%= lead_school.close_date&.strftime("%d %B %Y") %>
          </span>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<%= render Paginator::View.new(scope: @lead_schools) %>

app/views/system_admin/lead_schools/show.html.erb
<%= render PageTitle::View.new(text: @lead_school.name) %>

<%= content_for(:breadcrumbs) do %>
  <%= render GovukComponent::BackLinkComponent.new(
    text: t("back"),
    href: lead_schools_path,
  ) %>
<% end %>

<h1 class="govuk-heading-l"><%= @lead_school.name %></h1>

<dl class="govuk-summary-list">
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      URN
    </dt>
    <dd class="govuk-summary-list__value">
      <%= @lead_school.urn %>
    </dd>
  </div>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Town
    </dt>
    <dd class="govuk-summary-list__value">
      <%= @lead_school.town %>
    </dd>
  </div>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Postcode
    </dt>
    <dd class="govuk-summary-list__value">
      <%= @lead_school.postcode %>
    </dd>
  </div>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Open date
    </dt>
    <dd class="govuk-summary-list__value">
      <%= @lead_school.open_date&.strftime("%d %B %Y") %>
    </dd>
  </div>
  <div class="govuk-summary-list__row">
    <dt class="govuk-summary-list__key">
      Close date
    </dt>
    <dd class="govuk-summary-list__value">
      <%= @lead_school.close_date&.strftime("%d %B %Y") %>
    </dd>
  </div>
</dl>