config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  extend SystemAdminRoutes
  extend ApiRoutes

  get :ping, controller: :heartbeat
  get :healthcheck, controller: :heartbeat
  get :sha, controller: :heartbeat

  get "/accessibility", to: "pages#accessibility", as: :accessibility
  get "/privacy-policy", to: "pages#privacy_policy", as: :privacy_policy
  get "/guidance", to: "pages#guidance"
  get "/check-data", to: "pages#check_data"

  get "/404", to: "errors#not_found", via: :all, as: :not_found
  get "/422", to: "errors#unprocessable_entity", via: :all
  get "/500", to: "errors#internal_server_error", via: :all

  get "/trainees/not-supported-route", to: "trainees/not_supported_routes#index"

  get "/sign-in" => "sign_in#index"
  get "/sign-out" => "sign_out#index"

  get "/sign-in/user-not-found", to: "sign_in#new"

  get "request-an-account", to: "request_an_account#index"

  if FeatureService.enabled?("use_dfe_sign_in")
    get "/auth/dfe/callback" => "sessions#callback"
    get "/auth/dfe/sign-out" => "sessions#signout"
  else
    get "/personas", to: "personas#index"
    get "/auth/developer/sign-out", to: "sessions#signout"
    post "/auth/developer/callback", to: "sessions#callback"
  end

  concern :confirmable do
    resource :confirm_details, as: :confirm, only: %i[show update], path: "/confirm", controller: "/trainees/confirm_details"
  end

  resources :drafts, only: :index

  resources :trainees, except: :edit do
    scope module: :trainees do
      resource :training_details, concerns: :confirmable, only: %i[edit update], path: "/training-details"
      resource :course_years, only: %i[edit update], path: "/course-years"
      resource :publish_course_details, only: %i[edit update], path: "/publish-course-details" do
        concerns :confirmable
      end

      resource :course_details, only: %i[edit update], path: "/course-details" do
        concerns :confirmable
        resource :itt_dates, only: %i[edit update], path: "/itt-dates"
        resource :study_mode, only: %i[edit update], path: "/study-mode"
      end

      resource :confirm_deletes, only: :show, path: "/confirm-delete", as: :confirm_delete
      resource :check_details, only: :show, path: "/check-details"
      resource :review_drafts, only: :show, path: "/review-draft"
      resource :course_details, only: %i[edit update], path: "/course-details", path_names: { edit: "" }
      resource :publish_course_details, only: %i[edit update], path: "/publish-course-details", path_names: { edit: "" }

      resource :schools, concerns: :confirmable, only: %i[edit update], path: "/schools"
      resource :contact_details, concerns: :confirmable, only: %i[edit update], path: "/contact-details"
      resource :start_date, concerns: :confirmable, only: %i[edit update], path: "/trainee-start-date"
      resource :start_status, concerns: :confirmable, only: %i[edit update], path: "/trainee-start-status"
      resource :training_route, only: %i[edit update], path: "/training-routes"
      resource :course_education_phase, only: %i[edit update], path: "/course-education-phase"

      namespace :degrees do
        resource :confirm_details, as: :confirm, only: %i[show update], path: "/confirm", controller: "confirm_details"
        get "/new/type", to: "type#new"
        post "/new/type", to: "type#create"
      end

      resources :degrees, only: %i[new edit create update destroy]

      namespace :funding do
        concerns :confirmable
        resource :training_initiative, only: %i[edit update], path: "/training-initiative"
        resource :bursary, only: %i[edit update], path: "/bursary"
      end

      resource :language_specialisms, only: %i[edit update], path: "/language-specialisms"

      resource :personal_details, concerns: :confirmable, only: %i[show edit update], path: "/personal-details"

      namespace :diversity do
        resource :confirm_details, as: :confirm, only: %i[show update], path: "/confirm", controller: "confirm_details"
        resource :disclosure, only: %i[edit update], path: "/information-disclosed"
        resource :ethnic_group, only: %i[edit update], path: "/ethnic-group"
        resource :ethnic_background, only: %i[edit update], path: "/ethnic-background"
        resource :disability_disclosure, only: %i[edit update], path: "/disability-disclosure"
        resource :disability_detail, only: %i[edit update], path: "/disabilities"
      end

      resource :outcome_details, only: [], path: "outcome-details" do
        get "confirm"
        get "recommended"
        resource :outcome_date, only: %i[edit update], path: "/outcome-date"
      end

      resource :award_recommendations, only: %i[create]

      resource :confirm_withdrawal, only: %i[show update], path: "/withdraw/confirm"
      resource :withdrawal, only: %i[show update], path: "/withdraw"

      resource :confirm_deferral, only: %i[show update], path: "/defer/confirm"
      resource :deferral, only: %i[show update], path: "/defer"

      resource :confirm_reinstatement, only: %i[show update], path: "/reinstate/confirm"
      resource :reinstatement, only: %i[show update], path: "/reinstate"

      resources :lead_schools, only: %i[index], path: "/lead-schools"
      resource :lead_schools, only: %i[update edit], path: "/lead-schools"
      resources :employing_schools, only: %i[index], path: "/employing-schools"
      resource :employing_schools, only: %i[update edit], path: "/employing-schools"

      namespace :apply_applications, path: "/apply-application" do
        resource :trainee_data, only: %i[update edit], path: "/trainee-data"
        resource :course_details, only: %i[update edit], path: "/course-details"
        resource :confirm_courses, only: %i[show update], path: "/confirm-course"
      end

      resource :timeline, only: :show

      resource :subject_specialism, only: %i[edit update], path: "/subject-specialism/:position"
      resource :start_date_verification, only: %i[show update], path: "/start-date-verification"
      resource :forbidden_deletes, only: %i[show create], path: "/delete-forbidden"
      resource :forbidden_withdrawal, only: %i[show], path: "/withdrawal-forbidden"
    end
  end

  resources :trn_submissions, only: %i[create show], param: :trainee_id, path: "trainee-registrations"
  resource :cookie_preferences, only: %i[show update], path: "/cookies"

  resources :service_updates, only: %i[index], path: "service-updates"

  root to: "pages#start"
end

app/controllers/trainees/apply_applications/confirm_courses_controller.rb
# frozen_string_literal: true

module Trainees
  module ApplyApplications
    class ConfirmCoursesController < BaseController
      before_action :redirect_to_manual_confirm_page, if: :manual_entry_chosen?
      before_action :set_course, :set_specialisms

      helper_method :course_uuid

      def show
        page_tracker.save_as_origin!
        @confirm_course_form = ::ApplyApplications::ConfirmCourseForm.new(trainee, @specialisms)
      end

      def update
        @confirm_course_form = ::ApplyApplications::ConfirmCourseForm.new(trainee, @specialisms, course_params)

        if @confirm_course_form.save
          clear_form_stash(trainee)
          redirect_to(trainee_review_drafts_path(trainee))
        else
          render(:show)
        end
      end

    private

      def redirect_to_manual_confirm_page
        redirect_to(trainee_course_details_confirm_path(trainee))
      end

      def set_course
        @course = trainee.available_courses.find_by(code: course_uuid)
      end

      def set_specialisms
        @specialisms = if trainee.course_subjects.any? && publish_course_details_form.course_uuid.nil?
                         trainee.course_subjects
                       else
                         selected_or_calculated_specialisms
                       end
      end

      def course_params
        params.require(:apply_applications_confirm_course_form)
              .permit(*::ApplyApplications::ConfirmCourseForm::FIELDS)
      end

      def course_uuid
        publish_course_details_form.course_uuid || trainee.course_uuid
      end

      def publish_course_details_form
        @publish_course_details_form ||= PublishCourseDetailsForm.new(trainee)
      end

      def selected_or_calculated_specialisms
        if publish_course_details_form.selected_specialisms.any?
          publish_course_details_form.selected_specialisms
        else
          CalculateSubjectSpecialisms.call(subjects: @course.subjects.pluck(:name)).values.map(&:first).compact
        end
      end

      def manual_entry_chosen?
        publish_course_details_form.manual_entry_chosen? || trainee.course_uuid.blank?
      end
    end
  end
end

app/controllers/trainees/apply_applications/course_details_controller.rb
# frozen_string_literal: true

module Trainees
  module ApplyApplications
    class CourseDetailsController < BaseController
      before_action :set_course
      before_action :redirect_to_confirm_page, if: :already_confirmed_course?
      before_action :redirect_to_publish_course_details_path, if: :course_not_found?

      def edit
        @review_course_form = ::ApplyApplications::ReviewCourseForm.new
      end

      def update
        @review_course_form = ::ApplyApplications::ReviewCourseForm.new(review_course_params)

        if @review_course_form.valid?
          return save_course_and_continue if @review_course_form.registered?

          redirect_to(edit_trainee_publish_course_details_path(trainee))
        else
          render(:edit)
        end
      end

    private

      def review_course_params
        params.require(:apply_applications_review_course_form).permit(
          *::ApplyApplications::ReviewCourseForm::FIELDS,
        )
      end

      def set_course
        @course = trainee.published_course
      end

      def subject_specialism_path
        return edit_trainee_language_specialisms_path(trainee) if specialism_type == :language

        edit_trainee_subject_specialism_path(trainee, 1)
      end

      def specialism_type
        @specialism_type ||= CalculateSubjectSpecialismType.call(subjects: course_subjects)
      end

      def course_has_one_specialism?
        specialisms.all? { |_, v| v.count < 2 }
      end

      def specialisms
        @specialisms ||= CalculateSubjectSpecialisms.call(subjects: course_subjects)
      end

      def course_subjects
        @course_subjects ||= @course.subjects.pluck(:name)
      end

      def redirect_to_confirm_page
        redirect_to(trainee_apply_applications_confirm_courses_path(trainee))
      end

      def redirect_to_publish_course_details_path
        redirect_to(edit_trainee_publish_course_details_path(trainee))
      end

      def save_course_and_continue
        save_course
        redirect_to_relevant_step
      end

      def save_course
        ::ApplyApplications::ConfirmCourseForm.new(
          trainee,
          course_has_one_specialism? ? specialisms : [],
          { uuid: review_course_params[:uuid] },
        ).save
      end

      def redirect_to_relevant_step
        if specialisms.size > 1
          redirect_to(subject_specialism_path)
        else
          redirect_to(trainee_apply_applications_confirm_courses_path(trainee))
        end
      end

      def already_confirmed_course?
        trainee.course_subjects.any?
      end

      def course_not_found?
        @course.blank?
      end
    end
  end
end

app/controllers/trainees/apply_applications/trainee_data_controller.rb
# frozen_string_literal: true

module Trainees
  module ApplyApplications
    class TraineeDataController < BaseController
      before_action :require_review_acknowledgement, only: :update

      def edit
        page_tracker.save_as_origin!
        @trainee = trainee
        @trainee_data_form = trainee_data_form
        @invalid_data_view = invalid_data_view
      end

      def update
        @trainee = trainee
        @trainee_data_form = trainee_data_form
        @invalid_data_view = ApplyInvalidDataView.new(trainee.apply_application)

        if @trainee_data_form.save
          redirect_to(trainee_path(trainee))
        else
          render(:edit)
        end
      end

    private

      def trainee_data_form
        @trainee_data_form ||= ::ApplyApplications::TraineeDataForm.new(trainee)
      end

      def invalid_data_view
        @invalid_data_view ||= ApplyInvalidDataView.new(trainee.apply_application, degrees_sort_order: trainee.degrees.pluck(:slug))
      end

      def require_review_acknowledgement
        redirect_to(trainee_review_drafts_path(trainee)) unless marked_as_reviewed?
      end

      def marked_as_reviewed?
        params[:apply_applications_trainee_data_form][:mark_as_reviewed] == "1"
      end
    end
  end
end

app/controllers/trainees/award_recommendations_controller.rb
# frozen_string_literal: true

module Trainees
  class AwardRecommendationsController < BaseController
    def create
      if OutcomeDateForm.new(trainee).save! && trainee.submission_ready?
        trainee.recommend_for_award!

        Dttp::RecommendForAwardJob.perform_later(trainee)
        Dttp::RetrieveAwardJob.perform_with_default_delay(trainee)

        redirect_to(recommended_trainee_outcome_details_path(trainee))
      end
    end

  private

    def authorize_trainee
      authorize(trainee, :recommend_for_award?)
    end
  end
end

app/controllers/trainees/base_controller.rb
# frozen_string_literal: true

module Trainees
  class BaseController < ApplicationController
    before_action :authorize_trainee

  private

    def trainee
      @trainee ||= Trainee.from_param(params[:trainee_id])
    end

    def authorize_trainee
      authorize(trainee)
    end
  end
end

app/controllers/trainees/check_details_controller.rb
# frozen_string_literal: true

module Trainees
  class CheckDetailsController < BaseController
    prepend_before_action :ensure_trainee_is_draft!

    def show
      page_tracker.save_as_origin!
      @form = Submissions::TrnValidator.new(trainee: trainee)
    end
  end
end

app/controllers/trainees/confirm_deferrals_controller.rb
# frozen_string_literal: true

module Trainees
  class ConfirmDeferralsController < BaseController
    def show
      page_tracker.save_as_origin!
      deferral_form
    end

    def update
      if deferral_form.save!
        trainee.defer!

        Dttp::DeferJob.perform_later(trainee)

        flash[:success] = "Trainee deferred"
        redirect_to(trainee_path(trainee))
      end
    end

  private

    def deferral_form
      @deferral_form ||= DeferralForm.new(trainee)
    end

    def authorize_trainee
      authorize(trainee, :defer?)
    end
  end
end

app/controllers/trainees/confirm_delete_controller.rb
# frozen_string_literal: true

module Trainees
  class ConfirmDeleteController < ApplicationController
    before_action :ensure_trainee_is_draft!
    before_action :authorize_trainee

    def show; end

  private

    def trainee
      @trainee ||= Trainee.from_param(params[:trainee_id])
    end

    def authorize_trainee
      authorize(trainee)
    end
  end
end

app/controllers/trainees/confirm_deletes_controller.rb
# frozen_string_literal: true

module Trainees
  class ConfirmDeletesController < BaseController
    def show; end
  end
end

app/controllers/trainees/confirm_reinstatements_controller.rb
# frozen_string_literal: true

module Trainees
  class ConfirmReinstatementsController < BaseController
    def show
      page_tracker.save_as_origin!
      reinstatement
    end

    def update
      if reinstatement.save! || trainee.starts_course_in_the_future?
        trainee.trn.present? ? trainee.receive_trn! : trainee.submit_for_trn!

        Dttp::ReinstateJob.perform_later(trainee)

        flash[:success] = "Trainee reinstated"
        redirect_to(trainee_path(trainee))
      end
    end

  private

    def reinstatement
      @reinstatement ||= ReinstatementForm.new(trainee)
    end
  end
end

app/controllers/trainees/confirm_withdrawals_controller.rb
# frozen_string_literal: true

module Trainees
  class ConfirmWithdrawalsController < BaseController
    def show
      page_tracker.save_as_origin!
      withdrawal
    end

    def update
      if withdrawal.save!
        trainee.withdraw!
        Dttp::WithdrawJob.perform_later(trainee)

        flash[:success] = "Trainee withdrawn"
        redirect_to(trainee_path(trainee))
      end
    end

  private

    def withdrawal
      @withdrawal ||= WithdrawalForm.new(trainee)
    end
  end
end

app/controllers/trainees/contact_details_controller.rb
# frozen_string_literal: true

module Trainees
  class ContactDetailsController < BaseController
    include Appliable

    def edit
      @contact_details_form = ContactDetailsForm.new(trainee)
    end

    def update
      @contact_details_form = ContactDetailsForm.new(trainee, params: contact_details_params, user: current_user)

      if @contact_details_form.stash_or_save!
        redirect_to(relevant_redirect_path)
      else
        render(:edit)
      end
    end

  private

    def contact_details_params
      params.require(:contact_details_form).permit(*ContactDetailsForm::FIELDS)
    end

    def relevant_redirect_path
      draft_apply_application? ? page_tracker.last_origin_page_path : trainee_contact_details_confirm_path(trainee)
    end
  end
end

app/views/trainees/course_details/_additional_subjects.html.erb
<details class="govuk-details" data-module="govuk-details" <% if f.object.has_additional_subjects? %> open<% end %>>
  <summary class="govuk-details__summary">
    <span class="govuk-details__summary-text">
      <%= t(".add_additional_subjects") %>
    </span>
  </summary>
  <div class="govuk-details__text">
    <p class="govuk-body"><%= t(".main_subject") %></p>

    <div class="govuk-!-margin-bottom-6 app-!-autocomplete--max-width-two-thirds ">

      <%= render FormComponents::Autocomplete::View.new(
        f,
        attribute_name: :course_subject_two,
        form_field: f.govuk_collection_select(
          :course_subject_two,
          course_subjects_options,
          :value,
          :text,
          label: { text: t(".subject_two") },
          hint: { text: t(".subject_hint") },
        ),
      ) %>
    </div>

    <div class="govuk-!-margin-bottom-6 app-!-autocomplete--max-width-two-thirds ">
      <%= render FormComponents::Autocomplete::View.new(
        f,
        attribute_name: :course_subject_three,
        form_field: f.govuk_collection_select(
          :course_subject_three,
          course_subjects_options,
          :value,
          :text,
          label: { text: t(".subject_three") },
          hint: { text: t(".subject_hint") },
        ),
      ) %>
    </div>

  </div>
</details>

app/views/trainees/course_details/_primary_phase.html.erb
<% if f.object.require_subject? %>
  <%= f.govuk_radio_buttons_fieldset(:primary_course_subjects,
                                     legend: { text: t(".subject_label"), size: "s" },
                                     classes: "age_range") do %>

    <% PUBLISH_PRIMARY_SUBJECTS.each_with_index do |age_range, index| %>
      <%= f.govuk_radio_button(:primary_course_subjects, age_range,
                               label: { text: age_range },
                               link_errors: index.zero?) %>
    <% end %>

    <%= f.govuk_radio_divider %>

    <%= f.govuk_radio_button(:primary_course_subjects,
                             :other,
                             label: { text: t(".primary_with_another_label") }) do %>

      <div class="govuk-!-margin-bottom-6 app-!-autocomplete--max-width-two-thirds ">

        <%= render FormComponents::Autocomplete::View.new(
          f,
          attribute_name: :course_subject_two,
          form_field: f.govuk_collection_select(
            :course_subject_two,
            course_subjects_options,
            :value,
            :text,
            label: { text: t(".subject_two") },
            hint: { text: t(".subject_hint") },
          ),
        ) %>
      </div>

      <div class="govuk-!-margin-bottom-6 app-!-autocomplete--max-width-two-thirds ">
        <%= render FormComponents::Autocomplete::View.new(
          f,
          attribute_name: :course_subject_three,
          form_field: f.govuk_collection_select(
            :course_subject_three,
            course_subjects_options,
            :value,
            :text,
            label: { text: t(".subject_three") },
            hint: { text: t(".subject_hint") },
          ),
        ) %>
      </div>

    <% end %>
  <% end %>
<% end %>

app/views/trainees/course_details/_secondary_phase.html.erb
<% if f.object.require_subject? %>
  <%= render FormComponents::Autocomplete::View.new(
    f,
    attribute_name: :course_subject_one,
    form_field: f.govuk_collection_select(
      :course_subject_one,
      course_subjects_options,
      :value,
      :text,
      label: { text: t(".subject_label"), size: "s" },
      hint: { text: t(".subject_hint") },
    ),
  ) %>

  <%= render "additional_subjects", f: f %>
<% end %>

app/views/trainees/course_details/edit.html.erb
<%= render PageTitle::View.new(i18n_key: "trainees.course_details.edit", has_errors: @course_details_form.errors.present?) %>

<%= content_for(:breadcrumbs) do %>
  <%= render DynamicBackLink::View.new(@trainee, text: t(:back)) %>
<% end %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds-from-desktop">

    <%= register_form_with(model: @course_details_form, url: trainee_course_details_path(@trainee), method: :put, local: true) do |f| %>

      <%= f.govuk_error_summary %>

      <%= render TraineeName::View.new(@trainee) %>
      <h1 class="govuk-heading-l"><%= t(".heading") %></h1>

      <% if f.object.is_primary_phase? %>
        <%= render "primary_phase", f: f %>
      <% else %>
        <%= render "secondary_phase", f: f %>
      <% end %>

      <% if f.object.require_age_range? %>
        <%= f.govuk_radio_buttons_fieldset(:main_age_range,
                                           legend: { text: t(".age_range_label"), size: "s" },
                                           classes: "age_range") do %>

          <% main_age_ranges_options(level: @course_details_form.course_education_phase).each_with_index do |age_range, index| %>
            <%= f.govuk_radio_button(:main_age_range, age_range,
                                     label: { text: age_range },
                                     link_errors: index.zero?) %>
          <% end %>

          <%= f.govuk_radio_divider %>

          <%= f.govuk_radio_button(:main_age_range,
                                   :other,
                                   label: { text: t(".other_age_range_label") }) do %>

            <%= f.govuk_collection_select(:additional_age_range,
                                          additional_age_ranges_options(level: @course_details_form.course_education_phase),
                                          :value,
                                          :text,
                                          label: { text: t(".additional_age_range_label") }) %>

          <% end %>
        <% end %>
      <% end %>

      <% if f.object.requires_study_mode? %>
        <%= f.govuk_radio_buttons_fieldset(:study_mode, legend: { text: t(".study_mode_label"), size: "s" }) do %>
          <%= f.govuk_radio_button :study_mode, COURSE_STUDY_MODES[:full_time], label: { text: t(".study_mode_full_time") }, link_errors: true %>
          <%= f.govuk_radio_button :study_mode, COURSE_STUDY_MODES[:part_time], label: { text: t(".study_mode_part_time") } %>
        <% end %>
      <% end %>

      <%= f.govuk_date_field(:itt_start_date,
                             date_of_birth: false,
                             legend: { text: t("publish_course_details.view.itt_start_date").html_safe, size: "s" },
                             hint: { text: t("activemodel.errors.models.course_details_form.attributes.itt_start_date.hint_html", year: Time.zone.now.year) }) %>

       <%= f.govuk_date_field(:itt_end_date,
                              date_of_birth: false,
                              legend: { text: t("publish_course_details.view.itt_end_date").html_safe, size: "s" },
                              hint: { text: t("activemodel.errors.models.course_details_form.attributes.itt_end_date.hint_html", year: Time.zone.now.next_year.year) }) %>

      <%= f.govuk_submit %>
    <% end %>
  </div>
</div>

<%= render(CancelLink::View.new(@trainee)) %>